### ISSUE TITLE
Peer to Peer Code  Review

### ISSUE THREAD

**Issue by DamianDib9** [Jawad-Nazari/Awsome-book#2]
### Hi @Khaled-Alaa-1  and @Jawad-Nazari  !
_________________________________________
**I see that you have made a great work but kindly consider fixing this linters error.**
![image](https://user-images.githubusercontent.com/121461459/228268739-ba90cb83-9386-4283-a719-6dc596d99928.png)
  
 _Happy coding! 😎👍_

**Comment by DamianDib9** [comment]
@Jawad-Nazari  Thanks for the title fixing. My bad

**Comment by Jawad-Nazari** [comment]
The issue is resolved.
